name: hw1_env
dependencies:
    - python=3.8
    - pip
    - pip:
        - numpy==1.18.5
        - pandas==1.4.2
        - seaborn==0.11.2
        - matplotlib==3.5.1
        - scikit-learn==0.23.1
        - torch==1.11.0
        - lime==0.2.0.1
